import { Html, Head, Main, NextScript } from "next/document";

export const metadata = {
  title: "TravelLand",
  name: "description",
  content: "travel every where you want to go to",
  description: "Generated by create next app",
};

export default function Document() {
  return (
    <Html lang="en">
      <Head/>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}


